#15 fix action lint errors

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -182,64 +182,58 @@ jobs:
       - name: Get errors count
         # echo "ERROR_COUNT=grep -E 'name=\"/home/ubuntu' phpunit-report.xml | grep -o -P '(?<=errors=\").*(?=\" fail)'" >> "$GITHUB_ENV"
         # echo $(ERROR_COUNT=grep -E 'name=\"/home/ubuntu' phpunit-report.xml | grep -o -P '(?<=errors=\").*(?=\" fail)') >> "$GITHUB_ENV"
-        run: "|
-          echo $(ERROR_COUNT=grep -E 'name=\"/home/' .artifacts/phpunit-report.xml | grep -o -P '(?<=errors=\").*(?=\" fail)') >> '$GITHUB_ENV'"
+        run: |
+          "echo $(ERROR_COUNT=grep -E 'name=\"/home/' .artifacts/phpunit-report.xml | grep -o -P '(?<=errors=\").*(?=\" fail)') >> '$GITHUB_ENV'"
 
       - name: Get failures count
         id: failures-count
         # echo "FAILURE_COUNT=grep -E 'name=\"/home/ubuntu' phpunit-report.xml | grep -o -P '(?<=failures=\").*(?=\" skipped)'" >> "$GITHUB_ENV"
         # echo $(FAILURE_COUNT=grep -E 'name=\"/home/ubuntu' phpunit-report.xml | grep -o -P '(?<=failures=\").*(?=\" skipped)') >> "$GITHUB_ENV"
         # echo $(FAILURE_COUNT=grep -E 'name=\"/home/ubuntu' phpunit-report.xml | grep -o -P '(?<=failures=\").*(?=\" skipped)')
-        run: "|
-          ls -la
-          ls -la .artifacts
-          cat .artifacts/phpunit-report.xml
-          echo 'failure count'
-          echo $(grep -E 'name=\"/home/' .artifacts/phpunit-report.xml | grep -o -P '(?<=failures=\").*(?=\" skipped)')
-          echo $(FAILURE_COUNT=grep -E 'name=\"/home/' .artifacts/phpunit-report.xml | grep -o -P '(?<=failures=\").*(?=\" skipped)') >> '$GITHUB_ENV'"
-          # echo "" | grep -E "name=\"/home/" ./.artifacts/phpunit-report.xml
-          # echo "" | "$(grep -E "name=\"/home/" .artifacts/phpunit-report.xml | grep -o -P "(?<=failures=\").*(?=" failures)")"
-          # echo $(FAILURE_COUNT=grep -E "name=\"/home/" .artifacts/phpunit-report.xml | grep -o -P "(?<=failures=\").*(?=" skipped)")
-          # echo "nach auskommentiert..."
-          # echo "$FAILURE_COUNT"
-          # echo "$FAILURE_COUNT" >> "$GITHUB_ENV"
+        run: |
+          "ls -la" \
+          "ls -la .artifacts" \
+          "cat .artifacts/phpunit-report.xml" \
+          "echo 'failure count'" \
+          "echo $(grep -E 'name=\"/home/' .artifacts/phpunit-report.xml | grep -o -P '(?<=failures=\").*(?=\" skipped)')" \
+          "echo $(FAILURE_COUNT=grep -E 'name=\"/home/' .artifacts/phpunit-report.xml | grep -o -P '(?<=failures=\").*(?=\" skipped)') >> '$GITHUB_ENV'"
 
       - name: Get skipped count
         # echo "SKIPPED_COUNT=grep -E 'name=\"/home/ubuntu' phpunit-report.xml | grep -o -P '(?<=skipped=\").*(?=\" time)'" >> "$GITHUB_ENV"
         # echo $(SKIPPED_COUNT=grep -E 'name=\"/home/ubuntu' phpunit-report.xml | grep -o -P '(?<=skipped=\").*(?=\" time)') >> "$GITHUB_ENV"
-        run: "|
-          echo $(SKIPPED_COUNT=grep -E 'name=\"/home/' .artifacts/phpunit-report.xml | grep -o -P '(?<=skipped=\").*(?=\" time)') >> '$GITHUB_ENV'"
+        run: |
+          "echo $(SKIPPED_COUNT=grep -E 'name=\"/home/' .artifacts/phpunit-report.xml | grep -o -P '(?<=skipped=\").*(?=\" time)') >> '$GITHUB_ENV'"
 
       - name: Transform test report to CTRF
-        run: "|
-          npx junit-to-ctrf .artifacts/phpunit-report.xml -o .artifacts/phpunit-report.ctrf.json"
+        run: |
+          "npx junit-to-ctrf .artifacts/phpunit-report.xml -o .artifacts/phpunit-report.ctrf.json"
 
       - name: Generate test summary
-        run: "|
-          npx github-actions-ctrf summary .artifacts/phpunit-report.ctrf.json"
+        run: |
+          "npx github-actions-ctrf summary .artifacts/phpunit-report.ctrf.json"
 
       - name: Generate failed summary
         if: env.FAILURE_COUNT != '0'
-        run: "|
-          echo 'should add failed summary' 
-          npx github-actions-ctrf failed .artifacts/phpunit-report.ctrf.json"
+        run: |
+          "echo 'should add failed summary'" \
+          "npx github-actions-ctrf failed .artifacts/phpunit-report.ctrf.json"
 
       - name: Generate skipped summary
         if: env.SKIPPED_COUNT != '0'
-        run: "|
-          echo 'should add skipped summary' 
-          npx github-actions-ctrf skipped .artifacts/phpunit-report.ctrf.json"
+        run: |
+          "echo 'should add skipped summary'" \ 
+          "npx github-actions-ctrf skipped .artifacts/phpunit-report.ctrf.json"
 
       - name: Generate tests list
-        run: "|
-          echo 'err: ' ${{ env.ERROR_COUNT }}
-          echo 'fail: ' ${{ env.FAILURE_COUNT }}
-          echo 'should add tests list' 
-          npx github-actions-ctrf tests .artifacts/phpunit-report.ctrf.json"
+        run: |
+          "echo 'err: ' ${{ env.ERROR_COUNT }}" \
+          "echo 'fail: ' ${{ env.FAILURE_COUNT }}" \
+          "echo 'should add tests list' " \
+          "npx github-actions-ctrf tests .artifacts/phpunit-report.ctrf.json"
 
       - name: Fail pipeline
         if: env.ERROR_COUNT != '0' || env.FAILURE_COUNT != '0'
-        run: "|
-          echo 'err: ' ${{ env.ERROR_COUNT }}
-          echo 'fail: ' ${{ env.FAILURE_COUNT }}
-          exit 1"
+        run: |
+          "echo 'err: ' ${{ env.ERROR_COUNT }}" \
+          "echo 'fail: ' ${{ env.FAILURE_COUNT }}" \
+          "exit 1"
