#15 add debug info

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -212,4 +212,7 @@ jobs:
 
       - name: Fail pipeline
         if: env.ERROR_COUNT != '0' || env.FAILURE_COUNT != '0'
-        run: exit 1
+        run: |
+          echo "err: " ${{ env.ERROR_COUNT }}
+          echo "fail: " ${{ env.FAILURE_COUNT }}
+          exit 1
